application:
  version: 1.0
server:
  port: 9105

logging:
  file:
    name: log/app.log
    max-size: 10MB
    max-history: 20
  level:
    ROOT: INFO
    org.springframework: DEBUG
    com.skillbox.sw: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/weathertracker
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      auto-commit: true
      connectionTimeout: 60000
      maximumPoolSize: 50
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

apiKey: ac8202174d44d5907d95d3c2ddfa7782